name: Tests

on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "**.rs"
      - ".github/workflows/**.yml"
      - "dev-requirements.txt"

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.py"
      - "**.rs"
      - ".github/workflows/**.yml"
      - "dev-requirements.txt"

jobs:
  python-tests:
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          pip install --upgrade --user pip
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-py${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-py${{ matrix.python-version }}-
      - name: Install CPU Torch
        if: runner.os != 'macos'
        run: |
          pip install torch==1.8.1+cpu torchvision==0.9.1+cpu torchcsprng==0.2.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
        shell: bash
      - name: Install dependencies
        run: |
          hash -r
          pip install -r dev-requirements.txt -f https://download.pytorch.org/whl/torch_stable.html
          pip install -e .
        shell: bash
      - id: file_changes # get changed files.
        uses: jitterbit/get-changed-files@v1
        with:
          format: space-delimited

      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --files ${{ steps.file_changes.outputs.all }} # apply only to changed files.

      - name: Check docstring coverage
        run: |
          interrogate -mvp src/ -f 80

      - name: Scan for security issues
        run: |
          bandit -r src
          safety check

      - name: Run tests
        run: |
          pytest test/ -n 8 -x

  rust-tests:
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test